### ISSUE TITLE
warrior tokens use different picture link scheme than eldrazi spawn

### ISSUE THREAD

**Issue by tooomm** [Psithief/Cockatrice-tokens#7]
I noticed by random, when looking at the new MM tokens, that you included all three versions of the card art there. Each with a separate token (all the **same data!** just different art!)
![untitled](https://cloud.githubusercontent.com/assets/9874850/7566709/addbff90-f7f8-11e4-88b9-7f33a5a928dc.png)

`spawn1`, `spawn2_`, `spawn3__`, with a additional "_" attached to make it a separate new token.

But for warrior tokens for example *(their might be other examples with different art for technically the same token within one set as well)* you have both arts within the same white 1/1 token.
One of them commented out.

I think I like the warrior way better than the eldrazi spawn way, because it narrows the token count down and you don't see 3 times a eldrazi spawn in your list with the same data. Just by name you can't distinguish between the card art anyway... It's confusing as well if you click different list entries with the same name and they have all he same data.

I like that you include them, so people can have a look and easily adjust the file for themselves!
But which to comment out by default?
The one with the higher card count in the bottom left corner?
Or the one which you think looks worse?
Or... :)

Maybe you could add a bit more information to the comment like this as well: :+1: 
```
<card>
            <name>Warrior </name>
            <set picURL="http://media.wizards.com/2015/dftyuvbd564776rvf/en_zFodI6VkI0.png">DTK</set>
            <set picURL="http://media.wizards.com/images/magic/tcg/products/ktk/8arg43u984398yf/en_9uro1jblrh.png">KTK</set>
            <!-- alternate art token from KTK set (#004)
            <set picURL="http://media.wizards.com/images/magic/tcg/products/ktk/8arg43u984398yf/en_pfcpv8y40h.png">KTK</set>
            -->
            <color>W</color>
```
(the card number is just an idea for further discriminability)
(keep it clean, simple and obvious)

If you think the "warrior way" is better, do you know of any other tokens that might be splitted up like the spawn just for the cart art reason?

<br>
---
Thanks for the quick fixes and adjustments in the last days btw!

**Comment by Psithief** [comment]
The multiple Eldrazi Spawn are there for legacy reasons. Again, that's how it was when I found it.
My reason for keeping them as such was the off-chance that some people already have these tokens in their decks, and by removing them I am breaking their token list.

The warriors were added by me, so they don't follow that pattern. Additionally, warriors are less important themantically to Magic. :+1: 

---

Now, the main reason I don't have XML comments with additional text is because I added them with a shortcut key in my editor. If I add text after the opening comment tag, then I can't remove the comment with the same shortcut without also being forced to manually select and delete that extra text.
For example:
```xml
<!-- alternate art token from KTK set (#004)
            <set picURL="http://media.wizards.com/images/magic/tcg/products/ktk/8arg43u984398yf/en_pfcpv8y40h.png">KTK</set>
            -->
```
would become:
```xml
alternate art token from KTK set (#004)
            <set picURL="http://media.wizards.com/images/magic/tcg/products/ktk/8arg43u984398yf/en_pfcpv8y40h.png">KTK</set>
            
```
and so adding text that might introduce markup errors at some point was something I wished to avoid.
As such, I want to avoid putting non-markup in comments where most of the editing takes place (`<set>`).

---
I'm not planning on revisiting the issue until the Cockatrice team wants to address the underlying issue of the unique name problem.

> Daenyth commented on [31 Jul 2014](https://github.com/Cockatrice/Cockatrice/issues/241#issuecomment-50668413)
I don't consider "space in cardname to distinguish them" to be "solved". It's a hack that does work for now, but I'd really prefer a smarter solution.

**Comment by tooomm** [comment]
Thanks for the additional insight!

Having a solution for unique names would be great for sure.
But I still think that improving/evolving things and removing failures or tiding things up, no matter who has been responsible for it, is more important than keeping backwards compatibility for a few. They can easily fix as well.

**Comment by Psithief** [comment]
There's one for each brood: Ulamog's, Kozilek's and Emrakul's. That's why all three were reprinted.

**Comment by tooomm** [comment]
Just for the record:
Isn't it the same with the warrior tokens in KTK?
One is more Abzan, the other is more Mardu flavored? ;)

I guess that's the general purpose of printing several of the same tokens within one set/block, adjusting them to themes.

**Comment by Psithief** [comment]
If Cockatrice/Cockatrice#1445 is implemented soon I'll be tempted to change those spawn tokens to add "(ulamog)" / "(emrakul)" / "(kozilek)" suffixes.
